site_name: JEO Theme
pages:
  - 'Home': index.md
  - 'Gutenberg': gutenberg.md
  - 'Tooltip” style in the “Paragraph” block': tooltip.md
  - 'Credited Image” block': credit-image.md
  - 'Image gallery” block': image-gallery.md
  - 'Video gallery” block': video-gallery.md
  - 'Newsletter” block': newsletter.md
  - 'New style for the “Pullquote” block': pullquote.md
  - 'Content Box” block': content-box.md
  - 'Featured image': featured-image.md
  - 'Template: default, one column, one column wide': template.md 
  - 'Primary category': primary-category.md 
  - 'Categories': categories.md  
  - 'Tags': tags.md 
  - 'Author': author.md  
  - 'Republish link': republish-link.md 
  - 'External link': external-link.md 
  - 'New Yoast section location': new-yoast-location.md 
  - 'Sorry section': sorry-section.md 
  - 'Media partner republish link': media-partner.md 
  - 'Update home': update-home.md
  - 'Dark Mode': darkmode.md
  - 'Type Size options': type-size.md
  - 'General': general-configuration-panel.md
  - 'Site identity': site-identity.md
  - 'Colors': colors.md
  - 'Typography': typography.md
  - 'Menus': menus.md
  - 'Widgets': widgets.md
  - 'Homepage Settings': homepage-settings.md
  - 'Header Settings': header-settings.md
  - 'Autor Bio Settings': author-bio-settings.md
  - 'Template Settings': template-settings.md
  - 'Comment Settings': comment-settings.md
  - 'Footer Settings': fotter-settings.md
  - 'Post Sharing': post-sharing.md
  - 'Font size': font-size.md
  - 'Additional CSS': additional.css.md

theme: readthedocs